version: "3.9"

services:
  # server:
  #   build: .
  #   container_name: dash-server

  #   restart: always

  #   ports:
  #     - 3000:3000

  #   depends_on:
  #       - database

  adminer:
    image: adminer
    container_name: dash-adminer

    restart: always

    ports:
      - 5555:8080

    links:
      - database:db

  database:
    image: mysql:8.0
    container_name: dash-database

    restart: always

    ports:
      - 3306:3306

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dash

    volumes:
      - database-data:/var/lib/mysql

volumes:
  database-data:
